### ISSUE TITLE
garbled presets

### ISSUE THREAD

**Issue by severak** [mikerodd/june-21#1]
Hi,
I successfully compiled DLL for loading presets. It works sometimes. First few presets are OK, but after that it's garbled:

![garbled](https://user-images.githubusercontent.com/615685/69276730-43b88480-0bdf-11ea-93a1-ec3efdfba8eb.png)

I can provide [compiled standalone version](http://svita.cz/archiv/.tmp/june21-standalone.7z).

**Comment by mikerodd** [comment]
Corrected by the last commit on the loader
