### ISSUE TITLE
No sound via MIDI keyboard

### ISSUE THREAD

**Issue by m5g** [mikerodd/june-21#13]
v0.9.2, Windows 10 Pro x64
No sound via MIDI keyboard, same exe or dll, actually, keys is showing pressing by yellow color, but no sound, only by mouse clicking the piano keyboard inside plugin GUI.

**Comment by mikerodd** [comment]
do you use 0.9.2 ? 
In the exe  version, there is a button top left : Options -> Audio/Midi Settings -> Output 
try different output, use the test button to test if there is sound ?

**Comment by m5g** [comment]
I wrote before - if i clicking the piano keyboard inside plugin GUI by mouse - it plays sounds, pressing is visually confirmed by change the color key to yellow. but via MIDI - keys is pressing, i can see the color changing of a keys, but no sound, understand? )

**Comment by m5g** [comment]
Another comment from facebook by other member

"How to get this working? I installed it but as other pointed out...no sound, no MIDI signal. On it's own no sound, attempted to load sysx banks nothing appears."

**Comment by eisbaer23** [comment]
Probably related, using the VSTi wrapper, but I don't think that's the issue here, I have a similar problem when the Note On message has a velocity of 127. No sound. Other velocities play a note normally.

**Comment by mikerodd** [comment]
Thanks @eisbaer23  !  I'm uploading a new version (0.9.3) tell me if it solves your problem @m5g ?

**Comment by eisbaer23** [comment]
Ah. I was investigating a bit more the problem and found out that it only happened in "vcaenv" modes 0 and 1, modes 2 and 3 seem unaffected. But I'll try v0.9.3 in a few minutes.

**Comment by eisbaer23** [comment]
Myup, v0.9.3 fixes the Velocity 127 bug, for me, in all vcaenv modes. Thanks.

**Comment by m5g** [comment]
cant see 0.9.3 version )

**Comment by m5g** [comment]
Thanks! 0.9.3 fixes the issue! Many thanks
