### ISSUE TITLE
Samplerate is fixed to 44100 (notes out of tune if different)

### ISSUE THREAD

**Issue by eisbaer23** [mikerodd/june-21#14]
line 300, in june-21.csd
There is a fixed samplerate variable (well, constant...) to tune the notes to a rendering of 44.1kHz.
Using 24bit/48kHz myself in the DAW (Windows WASAPI default format is set to it and switching between different bit and samplerate between live mode and rendering introduces problems with some plugins) I was surprised at first with notes being out of tune. Setting the sr variable to 48000 fixed it. Would be nice to find a way to set this up automagically. :)
Also, take into account that sometimes people render at a different rate than using in live mode.

**Comment by mikerodd** [comment]
That's interesting :-) 
I don't know how to set this dynamically, i'm gonna have a look !

**Comment by mikerodd** [comment]
it seems there is a command-line option (--use-system-sr) that seems to do the trick (according to [this thread](https://listserv.heanet.ie/cgi-bin/wa?A2=ind1905&L=CSOUND&P=R1076&X=O655227FEFD9D5EDEEF)) in the last (6.13) CSound release.
I'm using 6.12beta, I'm going to make some test and see how handle this...

**Comment by mikerodd** [comment]
I suppressed sr, kr & kpms settings, in Ubuntu with jackd, csound seems to adapt to the host's sampling  rate (?)
Could you try by suppressing those too in Windows ?

**Comment by eisbaer23** [comment]
Seems to work fine. Added "--use-system-sr" in the CsOptions section and commented out the sr and ksmps constants, kr was already off. Tuning sounds okay so far across the keyboard. No need to fix the sr manually, yay!

**Comment by mikerodd** [comment]
Could you also try without the "--use-system-sr" option ? my version of CSound doesn't recognize it and yet, without any sr kr nor kpms it Cabbage managed to have a correct samplerate.
It would be a better solution as we would be 6.13 dependent

**Comment by eisbaer23** [comment]
Well. I deleted all those lines to be sure, tuning is fine at 48kHz.
