### ISSUE TITLE
Preset Recall/Management

### ISSUE THREAD

**Issue by eisbaer23** [mikerodd/june-21#15]
Okay, I have a problem using 2 instances of June-21 and modifying/creating presets for them.
VST Preset Recall seems to work, it does try to reload the presets or at least the bank and patch number, which I believe is all it is doing, right?
So, assuming all that is working is the copy-paste to the Sysex file I ran into a problem while using two instances in the DAW at the same time.
It would seem that only one of the instances can write to the Sysex files, maybe that instance is locking the files for itself? Not sure yet.
Also, working this way it means that if you're using the same Sysex file for both, everytime you change a parameter on another instance, an older version of the other patches is being written in the file. A way to handle this would be to only write the new patch, leaving the other untouched.
I'll do more tests to be sure it's not a problem on my end later.

**Comment by mikerodd** [comment]
> Okay, I have a problem using 2 instances of June-21 and modifying/creating presets for them.
VST Preset Recall seems to work, it does try to reload the presets or at least the bank and patch number, which I believe is all it is doing, right?
Yes, that's what it does
> maybe that instance is locking the files for itself? Not sure yet.
the file is open in write mode when it saved, but it's closed right after. 
In theory you shouldn't be able to write into the memory SYX (congrats you found another bug :-) ) but only in the "cartridge" slot.
My understanding of what you re saying is : 
instance 1 => sound p-11 => no modif    => copy    (delay)         =>  paste to c-11  
instance 2 => sound p-11 => modification => copy  => paste to c-11
this way you have the "old" preset (from instance 1) pasted and erasing the "new" one
Is it correct ?

**Comment by eisbaer23** [comment]
To use your example :
instance 1 => sound p-11 => modification => copy = paste to c-11
instance 2 => sound p-11 (or anything else) => other modification => copy = paste to c-12
The new c-11 from instance 1 gets overwritten by the old c-11 from instance 2.
Basically you can't share the USERCART.SYX, or at least I had troubles doing it.
Didn't do more research since. Maybe I should restart fresh to be sure.

**Comment by eisbaer23** [comment]
Before I go any further, it would be nice to have a tooltip on the File button, to know which SYX file is being used. Just like it works with parameters. Should be simple enough to add and very useful.

**Comment by eisbaer23** [comment]
It seems I was doing something wrong at some point, I've been doing many different experiments and couldn't reproduce the error, from a fresh project, at least so far. I'll be watching out for it (it's not funny losing your work).
I've been able to share both USERCART and another sysex file created especially for this purpose. Patches are shared from an instance to the other.

**Comment by eisbaer23** [comment]
Last follow-up on this one, probably.
Reloading the old problematic project, still a mess, cant work with it, so I did the sensible thing and deleted all instances, rebuilt a new sysex file using a bank manager (alphabase) from the salvaged sysex files I backuped prior with the only two patches I needed.
Reinserted the instances in the DAW, loaded the new (same) sysex file, and they live happily together again.
No clue what happened. But something happened.

**Comment by eisbaer23** [comment]
There's still something funky going on. Reloading the project files in the DAW.
One instance loads the EISBAER23.SYX bank fine, displays and plays the C-11 patch correctly.
The other displays and plays something else (from USERCART.SYX) until i change the patch to, say C-13, and then back to C-12 (the one it's supposed to load in the first place) loading correctly from the correct sysex file. Very strange.

**Comment by mikerodd** [comment]
I'll try to reproduce this last one here (Ubuntu / Ardour) tomorow

**Comment by mikerodd** [comment]
In ardour, I created 3 midi tracks with 3 instances (P-11, P-12,P-13), all three played the right sound. Saved, quit and back again, no problem.
Is it what you experienced with your DAW ?

**Comment by eisbaer23** [comment]
Using P and M works fine. Using C with an external file seems to be the problem here. Altho I first had troubles with the provided USERCART too. It seems USERCART is first loaded and then the preset in it is being used until you "refresh manually" by going back and forth on any other preset. But you don't have to reload the correct SYX, it already knows which one to use.

**Comment by mikerodd** [comment]
Yes I managed to reproduce. i'm on it

**Comment by eisbaer23** [comment]
Ah, so I'm not imagining the whole thing or a platform/DAW specific problem then. Sort of good to know. To be honest, I've had troubles reproducing the exact same error, it's not always the same instance doing it, If I start from scratch again it's either better or worse.
I wish I could be more precise.
Is there a way to check which SYX file is being used (or at least, should be)?

**Comment by mikerodd** [comment]
I updloaded a fix that seems to works better (tell me for you) 
in Ardour when I had 3 tracks pointing to 3 tones (in 2 different SYX) 
the display is correct and consistent but it some case (change syx, save, close open) it's not.
My guess is that DAWs keep some buffered state...

I'm also going to put the name of the SYX in the file button

**Comment by eisbaer23** [comment]
Had to fix the .so to .dll for the opcodes, at first it went very wrong. :-)
To be sure, I once again deleted all instances from the project, purge all the VST/Preset Recall data.
Reinserted three instances, pointed to my EISBAER23.SYX, three different tones.
Closed, reopened. Works for the first time as intended. :-)
Changed some parameters from all three tones, each from their own instance and all instances have direct access to them, so the file can be shared. That's great!

**Comment by mikerodd** [comment]
Cool 👍 
I close this one and open another to keep track of the weird behaviour I had in some case
