### ISSUE TITLE
[BUG] after one hour, this synth goes silent

### ISSUE THREAD

**Issue by severak** [mikerodd/june-21#18]
**Describe the bug**

after one hour, this synth goes silent without any warning. This can be really annoying at live concert.

**To Reproduce**

1. open instance of June-21 in your DAW
2. keep playing something ( testing presets) for one hour
3. synth is now silent

**Expected behavior**

```
i 100 0 [60*60*24*7]             ; run midi scanning for 1 week
```

(if you left DAW open for week you have mor problems than June going silent :smile: )

**Comment by mikerodd** [comment]
this one was easy to close ;-) !
