### ISSUE TITLE
saving presets

### ISSUE THREAD

**Issue by severak** [mikerodd/june-21#2]
It would be nice to have possibility to saving presets.

**Comment by severak** [comment]
I have idea how to implement it: There are two flawors of `.syx` files - one for whole banks and one for individual tones. Because implementing full UI for editing banks will be cumbersome, let's add just two buttons "save tone" and "load tone".

**Comment by mikerodd** [comment]
I think I'm going to make a virtual "Cartridge" with empty tones (that would be a .syx file) and 2 buttons : a copy (put current presets in a buffer) you go to the cartridge when you want to put it, the copy button is now a paste button and it pastes the tone in the cartridge selected tone
what do you think ?

**Comment by mikerodd** [comment]
Save is now available :-)
