### ISSUE TITLE
P11 - AAAAAAAAAA

### ISSUE THREAD

**Issue by severak** [mikerodd/june-21#6]
I am not sure if this is problem of June-21 or Element, but:

When loaded in Element VST host, June-21 shows `P11 - AAAAAAAAAA` as preset name, because no presets can be loaded. It looks like DLL is looking to wrong directory, because when you select cart file with `...` button, it loads presets (but still cannnot switch between PRESET and MEMORY).

In Ardour it loads fine.

**Comment by severak** [comment]
Also - when you save session in Element and reopen it - now it has proper behaviour - presets are automatically loaded.

**Comment by mikerodd** [comment]
I don't know this host, is it https://kushview.net/element/ ? 
I will try to reproduce the problem

**Comment by severak** [comment]
> I don't know this host, is it https://kushview.net/element/ ?

Exactly that one. On Windows.

**Comment by severak** [comment]
This is really weird - I tested it on another computer and it worked correctly.

**Comment by mikerodd** [comment]
Hey @severak, did you manage to get it work on your computer?

**Comment by severak** [comment]
@mikerodd it's probably something wrong with my setup. It depends on computer where I am testing it. We can probably close this and reopen it when somebody other experiences this.

**Comment by severak** [comment]
another computer and another VST host - this time [Tone2 nanohost](https://www.tone2.com/nanohost.html) and June is again the same problem.
