### ISSUE TITLE
proper windows package

### ISSUE THREAD

**Issue by severak** [mikerodd/june-21#9]
We should make proper windows package/installer similar as [Tone Z has](https://github.com/T0NIT0RMX/ToneZ/tree/master/InnoSetup). 

I can make it when I got some time in holidays. 

For now there is [june21.zip](https://github.com/mikerodd/june-21/files/3964296/june21.zip) which is win64 ready to use VST plugin. Note: You have to have CSound (or Cabbage or ToneZ) installed on your machine when using this.

**Comment by mikerodd** [comment]
I've made a Windows setup package which seems to work with Ubuntu/Wine  can you test it ?

**Comment by severak** [comment]
Working as expected.

I will just test it at my brother computer (where Csound/Cabbage is not installed), just to be sure about loading of Csound DLL.
